/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlansRouteImport } from './routes/plans'
import { Route as ProcessesRouteImport } from './routes/processes'
import { Route as RequirementsRouteImport } from './routes/requirements'
import { Route as ScenariosRouteImport } from './routes/scenarios'
import { Route as TestCasesRouteImport } from './routes/test-cases'
import { Route as RunsIndexRouteImport } from './routes/runs.index'
import { Route as RunsRunIdRouteImport } from './routes/runs.$runId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansRoute = PlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessesRoute = ProcessesRouteImport.update({
  id: '/processes',
  path: '/processes',
  getParentRoute: () => rootRouteImport,
} as any)
const RequirementsRoute = RequirementsRouteImport.update({
  id: '/requirements',
  path: '/requirements',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenariosRoute = ScenariosRouteImport.update({
  id: '/scenarios',
  path: '/scenarios',
  getParentRoute: () => rootRouteImport,
} as any)
const TestCasesRoute = TestCasesRouteImport.update({
  id: '/test-cases',
  path: '/test-cases',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsIndexRoute = RunsIndexRouteImport.update({
  id: '/runs/',
  path: '/runs/',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsRunIdRoute = RunsRunIdRouteImport.update({
  id: '/runs/$runId',
  path: '/runs/$runId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/plans': typeof PlansRoute
  '/processes': typeof ProcessesRoute
  '/requirements': typeof RequirementsRoute
  '/scenarios': typeof ScenariosRoute
  '/test-cases': typeof TestCasesRoute
  '/runs/$runId': typeof RunsRunIdRoute
  '/runs/': typeof RunsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/plans': typeof PlansRoute
  '/processes': typeof ProcessesRoute
  '/requirements': typeof RequirementsRoute
  '/scenarios': typeof ScenariosRoute
  '/test-cases': typeof TestCasesRoute
  '/runs/$runId': typeof RunsRunIdRoute
  '/runs': typeof RunsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/plans': typeof PlansRoute
  '/processes': typeof ProcessesRoute
  '/requirements': typeof RequirementsRoute
  '/scenarios': typeof ScenariosRoute
  '/test-cases': typeof TestCasesRoute
  '/runs/$runId': typeof RunsRunIdRoute
  '/runs/': typeof RunsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/plans'
    | '/processes'
    | '/requirements'
    | '/scenarios'
    | '/test-cases'
    | '/runs/$runId'
    | '/runs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/plans'
    | '/processes'
    | '/requirements'
    | '/scenarios'
    | '/test-cases'
    | '/runs/$runId'
    | '/runs'
  id:
    | '__root__'
    | '/'
    | '/plans'
    | '/processes'
    | '/requirements'
    | '/scenarios'
    | '/test-cases'
    | '/runs/$runId'
    | '/runs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PlansRoute: typeof PlansRoute
  ProcessesRoute: typeof ProcessesRoute
  RequirementsRoute: typeof RequirementsRoute
  ScenariosRoute: typeof ScenariosRoute
  TestCasesRoute: typeof TestCasesRoute
  RunsRunIdRoute: typeof RunsRunIdRoute
  RunsIndexRoute: typeof RunsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans': {
      id: '/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof PlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/processes': {
      id: '/processes'
      path: '/processes'
      fullPath: '/processes'
      preLoaderRoute: typeof ProcessesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requirements': {
      id: '/requirements'
      path: '/requirements'
      fullPath: '/requirements'
      preLoaderRoute: typeof RequirementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenarios': {
      id: '/scenarios'
      path: '/scenarios'
      fullPath: '/scenarios'
      preLoaderRoute: typeof ScenariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-cases': {
      id: '/test-cases'
      path: '/test-cases'
      fullPath: '/test-cases'
      preLoaderRoute: typeof TestCasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/': {
      id: '/runs/'
      path: '/runs'
      fullPath: '/runs/'
      preLoaderRoute: typeof RunsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/$runId': {
      id: '/runs/$runId'
      path: '/runs/$runId'
      fullPath: '/runs/$runId'
      preLoaderRoute: typeof RunsRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PlansRoute: PlansRoute,
  ProcessesRoute: ProcessesRoute,
  RequirementsRoute: RequirementsRoute,
  ScenariosRoute: ScenariosRoute,
  TestCasesRoute: TestCasesRoute,
  RunsRunIdRoute: RunsRunIdRoute,
  RunsIndexRoute: RunsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
